### ISSUE TITLE
Adding a FOSS license

### ISSUE THREAD

**Issue by ColinKennedy** [tommcdo/vim-ninja-feet#13]
Hi, I love and use this plug-in every day. It makes using Vim so much better! My workplace is cautious about allowing code without a `LICENSE` file and it'd be a big help if this plug-in could use a FOSS license. I'm sure others in the same position and would appreciate it too. Could a FOSS license please be added if this plug-in is meant for public use?

**Comment by tommcdo** [comment]
Hey Colin, I'm not opposed to that! I don't really have time to look into which license is appropriate, but I'd happily accept a pull request adding one in the spirit of "absolutely free for any purpose whatsoever".

**Comment by ColinKennedy** [comment]
Sure thing, I'll add a PR. Thank you for the quick reply! Most people prefer the MIT license because it's simple, concise, and basically boils down to

- Do whatever you want this this code
    - But include this license anywhere that you distribute this code
- The author of this code is not responsible for any issues

If you want people to be able to relicense (for commercial reasons or otherwise) then an Apache license is better, so I've read

**Comment by ColinKennedy** [comment]
@tommcdo I hope you don't mind if I add a license PR for https://github.com/tommcdo/vim-exchange as well, it's another one of my favorites!

**Comment by tommcdo** [comment]
Go for it! Thanks!
